### PR TITLE
Add some libraries

### PR DESCRIPTION
**Pull request by deedee**
-arena-shared-7.5.5
-concurrent-1.0.2
-custom-serialization-1.1.1
-logging-1.1.0
-basic_type_serialization-1.0.1

### CODE REVIEW

**Comment by skyhit** [comment]
@deedee what is this for?

**Comment by deedee** [comment]
It is from this challenge
https://www.topcoder.com/challenge-details/30057150/

Switching glue to not using coder.topcoder.com anymore. Copilot approved to add any missing dependecy here. Please consult with him

**Comment by skyhit** [comment]
cool

**Comment by sah2ed** [comment]
Thanks @deedee.

@skyhit,
I'd like to merge @deedee pull request into different branch from `master`.
Can you help create a new branch named `svn2git` from the master branch?

Once you are done, please post here so that @deedee can re-submit the pull request. Sorry for the trouble @deedee ;).

Thanks.

**Comment by skyhit** [comment]
@sah2ed no need to re-submit, I created the branch and switch to merge to that branch, do you need to merge this PR?

**Comment by sah2ed** [comment]
@skyhit yes, I need to merge it so I can test.

Thanks

**Comment by skyhit** [comment]
@sah2ed done

**Pull request merged**
